"""
Step 18 of the pipeline, and the last one: check that outputs/ matches
what the numbered scripts actually say they produce.

What this script does: every other numbered script in src/ declares, at
the top of its own file, an OUTPUT_FILES list naming exactly which files
under outputs/ it writes (and, for the one script whose output file names
depend on the data — 15_shap_dependence.py — an OUTPUT_FILE_PATTERNS list
of glob patterns instead). This script imports every one of those scripts,
reads their declarations, and compares the combined list against an actual
directory listing of outputs/. This design exists because an earlier
version of this script instead held its own separate, hand-maintained copy
of "which script produces which file," and that copy went stale
repeatedly — it claimed a working function was dead code, missed 18 real
files, and reported files as missing that were actually present, all
because nothing forced it to stay in sync with the scripts it was
describing. Reading each declaration from the script that owns it means
there is only one place to update when a script's outputs change, and a
mismatch between a declaration and reality shows up directly as an
orphaned, missing, or ambiguous entry below instead of silently producing
a wrong report.

Reads: nothing from outputs/audit/ or the manuscript — only the OUTPUT_FILES
/ OUTPUT_FILE_PATTERNS declarations in every other src/ script, and an
actual directory listing of outputs/.

Writes: output_manifest.csv.

Runs last, after every other script, so its directory listing reflects a
complete pipeline run.
"""

import fnmatch
import importlib.util
import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")
    sys.stderr.reconfigure(encoding="utf-8")

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import pandas as pd

from config import OUTPUTS

AUDIT_DIR = OUTPUTS / "audit"
MANIFEST_PATH = AUDIT_DIR / "output_manifest.csv"
SRC_DIR = Path(__file__).resolve().parent

OUTPUT_FILES = [
    "audit/output_manifest.csv",
]

# Every other numbered pipeline script. Listed explicitly (not discovered
# by scanning src/) so that adding a new script is a deliberate one-line
# change here, the same reasoning as data/facility_layers.txt in
# 05_accessibility.py — an auto-discovered list would silently include or
# exclude scripts based on what happens to be in the folder.
SCRIPT_STEMS = [
    "01_gi_construction", "02_road_network", "03_huff_ahp", "04_huff_nonweighted",
    "05_accessibility", "06_ml_framework", "07_beta_sensitivity", "08_euclidean_comparison",
    "09_entropy_uncertainty", "10_commuting_comparison", "11_export_outputs",
    "12_morans_lisa", "13_disagreement_synthesis", "14_ml_catchment_structure",
    "15_shap_dependence", "16_spatial_layers", "17_data_audit",
]

# Files legitimately present in outputs/ that no script produces, because
# they are maintained directly rather than regenerated. Each one needs an
# explicit reason here — anything not listed is treated as a real orphan
# (a genuine, unexplained mismatch) rather than a known exception.
KNOWN_NON_SCRIPT_OUTPUTS = {
    "supplementary/tableS2_AHP_priority_weights.csv":
        "The AHP pairwise comparison matrix is a judgment call, not a data-derived "
        "result — maintained directly in outputs/supplementary/, not regenerated by "
        "any script.",
    "tables/ml_AHP_feature_importance_original.csv":
        "Frozen pre-remediation baseline (committed 2026-08-11, predates this "
        "pipeline's own regeneration of ml_AHP_feature_importance.csv), kept for "
        "historical before/after comparison, not something any current script "
        "regenerates — same treatment as the outputs_archive_pre_*/ directories.",
    "tables/ml_AHP_vs_AHP_comparison_original.csv":
        "Frozen pre-remediation baseline (committed 2026-08-11, predates this "
        "pipeline's own regeneration of ml_AHP_vs_AHP_comparison.csv — the column "
        "layout itself differs, e.g. ahp_dominant_muni vs the current "
        "huff_dominant_muni), kept for historical before/after comparison, not "
        "something any current script regenerates.",
}


def load_module(stem):
    """Import src/NN_name.py by path, to read its module-level OUTPUT_FILES declaration.

    This only executes each script's top-level code (constants, function
    and class definitions), never its main() — every script guards its
    real work behind `if __name__ == "__main__":`, which is false here
    since the module is loaded under its own name, not as "__main__".
    """
    path = SRC_DIR / f"{stem}.py"
    spec = importlib.util.spec_from_file_location(stem, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def collect_declarations():
    """Import every pipeline script and gather what each one says it writes.

    Returns (claims, patterns): claims maps a relative outputs/ path to the
    list of script filenames that declared it via OUTPUT_FILES; patterns
    maps a script filename to the glob patterns it declared via
    OUTPUT_FILE_PATTERNS, for the rare script whose output file names
    depend on the data rather than being fixed in advance.
    """
    claims = {}
    patterns = {}
    for stem in SCRIPT_STEMS:
        script_name = f"{stem}.py"
        print(f"  Reading declarations from {script_name}...")
        mod = load_module(stem)
        for rel in getattr(mod, "OUTPUT_FILES", []):
            claims.setdefault(rel, []).append(script_name)
        script_patterns = getattr(mod, "OUTPUT_FILE_PATTERNS", [])
        if script_patterns:
            patterns[script_name] = script_patterns
    claims.setdefault("audit/output_manifest.csv", []).append("18_output_manifest.py")
    return claims, patterns


def main():
    print("=== OUTPUT MANIFEST ===")
    print()

    AUDIT_DIR.mkdir(parents=True, exist_ok=True)

    print("Importing every pipeline script to collect its OUTPUT_FILES declaration...")
    claims, patterns = collect_declarations()
    n_declared = sum(len(scripts) for scripts in claims.values())
    print(f"  {len(claims)} distinct files declared, {n_declared} total declarations "
          f"(more than the file count wherever two scripts claim the same file)")
    print()

    present = sorted(
        p.relative_to(OUTPUTS).as_posix()
        for p in OUTPUTS.rglob("*")
        if p.is_file() and p.name != ".gitkeep"
    )
    print(f"Files actually present in outputs/: {len(present)}")
    print()

    rows = []
    orphaned = []
    ambiguous = []
    for rel in present:
        scripts = list(claims.get(rel, []))

        if not scripts:
            for script_name, script_patterns in patterns.items():
                if any(fnmatch.fnmatch(rel, pat) for pat in script_patterns):
                    scripts.append(f"{script_name} (pattern match)")

        if not scripts and rel in KNOWN_NON_SCRIPT_OUTPUTS:
            producing = "(none — maintained directly, see KNOWN_NON_SCRIPT_OUTPUTS)"
        elif not scripts:
            orphaned.append(rel)
            producing = "ORPHANED — no script claims this file"
        elif len(scripts) > 1:
            ambiguous.append((rel, scripts))
            producing = " AND ".join(scripts) + "  [AMBIGUOUS — claimed by more than one script]"
        else:
            producing = scripts[0]

        rows.append({"path": f"outputs/{rel}", "producing_script": producing})

    missing = [
        (rel, scripts) for rel, scripts in claims.items()
        if not (OUTPUTS / rel).exists()
    ]

    df = pd.DataFrame(rows).sort_values("path").reset_index(drop=True)
    df.to_csv(MANIFEST_PATH, index=False)
    print(f"Saved {MANIFEST_PATH} ({len(df)} rows)")
    print()

    print(f"### Orphaned files — on disk, but no script or known exception claims them: {len(orphaned)}")
    for rel in orphaned:
        print(f"  - outputs/{rel}")
    print()

    print(f"### Ambiguous claims — more than one script claims the same file: {len(ambiguous)}")
    for rel, scripts in ambiguous:
        print(f"  - outputs/{rel}: {', '.join(scripts)}")
    print()

    print(f"### Missing files — a script claims this file, but it is not on disk: {len(missing)}")
    for rel, scripts in missing:
        print(f"  - outputs/{rel}  (claimed by {', '.join(scripts)})")
    print()

    if orphaned or ambiguous or missing:
        print("The pipeline output does not fully match what the scripts declare — "
              "see the sections above for exactly where.")
        print()
        print(f"=== FAILED: {len(orphaned)} orphaned, {len(ambiguous)} ambiguous, "
              f"{len(missing)} missing ===")
        sys.exit(1)

    print("Every declared file is present exactly once, and every present file "
          "is accounted for.")
    print()
    print("Done.")


if __name__ == "__main__":
    main()
